-- WDZX Oracle 数据库可行性审计：实际成功执行的只读证据 SQL
-- 审计日期：2026-09-16
-- 所有语句均通过 oracle_wdzx.execute_select 单独执行；MCP 调用时不带末尾分号。
-- 语句后的“limit”写在注释中，实际分页由 MCP 强制施加。
-- 不含任何连接串、密码、DDL、DML、存储过程或 EXPLAIN PLAN。

-- Q01（limit=5）：当前已上市有效 ETF 候选及审计日开/收盘集合竞价可成交数量。
WITH etf AS (
  SELECT DISTINCT c.S_INFO_WINDCODE
  FROM WDZX.CHINAETFINVESTCLASS c
  JOIN WDZX.CHINAMUTUALFUNDDESCRIPTION d
    ON d.F_INFO_WINDCODE = c.S_INFO_WINDCODE
  WHERE d.LISTEDFUNDORNOT = 1
    AND d.F_INFO_STATUS = 101001000
    AND d.F_INFO_LISTDATE <= '20260916'
    AND (d.F_INFO_DELISTDATE IS NULL OR d.F_INFO_DELISTDATE > '20260916')
    AND (c.S_INFO_WINDCODE LIKE '%.SH' OR c.S_INFO_WINDCODE LIKE '%.SZ')
)
SELECT COUNT(*) AS IDENTIFIED_LIVE_ETFS,
       COUNT(a.S_INFO_WINDCODE) AS WITH_AUCTION_ROW,
       COUNT(CASE WHEN a.OPEN_AUCTION_PRICE > 0 AND a.OPEN_AUCTION_VOLUME > 0 THEN 1 END) AS WITH_VALID_OPEN_AUCTION,
       COUNT(CASE WHEN a.CLOSE_AUCTION_PRICE > 0 AND a.CLOSE_AUCTION_VOLUME > 0 THEN 1 END) AS WITH_VALID_CLOSE_AUCTION
FROM etf e
LEFT JOIN WDZX.CHINACLOSEDFUNDAUCTION a
  ON a.S_INFO_WINDCODE = e.S_INFO_WINDCODE
 AND a.TRADE_DT = '20260916';

-- Q02（limit=5）：按 2023-06-01 生效区间重建 ETF 池，并验证包含后来退市的 515930.SH。
SELECT COUNT(DISTINCT s.F_INFO_WINDCODE) AS ETF_COUNT_AT_DATE,
       MAX(CASE WHEN s.F_INFO_WINDCODE = '515930.SH' THEN 1 ELSE 0 END) AS INCLUDES_LATER_DELISTED_ETF
FROM WDZX.CHINAMUTUALFUNDSECTOR s
JOIN WDZX.CHINAMUTUALFUNDDESCRIPTION d
  ON d.F_INFO_WINDCODE = s.F_INFO_WINDCODE
WHERE s.S_INFO_SECTOR = '2001020200'
  AND s.S_INFO_SECTORENTRYDT <= '20230601'
  AND (s.S_INFO_SECTOREXITDT IS NULL OR s.S_INFO_SECTOREXITDT > '20230601')
  AND d.F_INFO_LISTDATE <= '20230601'
  AND (d.F_INFO_DELISTDATE IS NULL OR d.F_INFO_DELISTDATE > '20230601')
  AND d.LISTEDFUNDORNOT = 1;

-- Q03（limit=50）：跟踪指数映射的生效/失效样例，包括已退市 ETF。
SELECT S_INFO_WINDCODE, S_INFO_INDEXWINDCODE, ENTRY_DT, REMOVE_DT, OPDATE, OPMODE
FROM WDZX.CHINAMUTUALFUNDTRACKINGINDEX
WHERE S_INFO_WINDCODE IN ('510300.SH','510310.SH','159919.SZ','159925.SZ','515930.SH')
ORDER BY S_INFO_WINDCODE, ENTRY_DT;

-- Q04（limit=5）：跟踪指数映射表的日期和字段覆盖。
SELECT COUNT(*) AS MAPPING_ROWS,
       COUNT(CASE WHEN ENTRY_DT IS NOT NULL THEN 1 END) AS WITH_ENTRY_DT,
       COUNT(CASE WHEN REMOVE_DT IS NOT NULL THEN 1 END) AS WITH_REMOVE_DT,
       COUNT(CASE WHEN S_INFO_INDEXWINDCODE IS NOT NULL THEN 1 END) AS WITH_INDEX_CODE,
       MIN(ENTRY_DT) AS MIN_ENTRY_DT,
       MAX(ENTRY_DT) AS MAX_ENTRY_DT,
       MAX(OPDATE) AS MAX_OPDATE
FROM WDZX.CHINAMUTUALFUNDTRACKINGINDEX
WHERE S_INFO_WINDCODE IS NOT NULL;

-- Q05（limit=50）：3 只中证 500 ETF 的业绩基准、权重、有效期和公告日。
SELECT S_INFO_WINDCODE, S_INFO_INDEXWINDCODE, S_INFO_BGNDT,
       S_INFO_ENDDT, S_INFO_INDEXWEG, CUR_SIGN, ANN_DT, S_INC_SEQUENCE
FROM WDZX.CHINAMUTUALFUNDBENCHMARK
WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
ORDER BY S_INFO_WINDCODE, S_INFO_BGNDT, S_INC_SEQUENCE;

-- Q06（limit=50）：3 只 ETF 的历史规模报告期与公告日样例。
SELECT S_INFO_WINDCODE, S_INFO_INNERCODE, S_INFO_OUTERCODE,
       F_PRT_ENDDATE, F_ANN_DATE, F_PRT_TOTALASSET, F_PRT_NETASSET,
       CRNCY_CODE, OPDATE
FROM WDZX.CHINAMUTUALFUNDASSETPORTFOLIO
WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
  AND F_PRT_ENDDATE BETWEEN '20241231' AND '20251231'
ORDER BY S_INFO_WINDCODE, F_PRT_ENDDATE;

-- Q07（limit=10）：3 只 ETF 的规模历史范围和公告日覆盖。
SELECT S_INFO_WINDCODE, MIN(F_PRT_ENDDATE) AS MIN_ENDDATE,
       MAX(F_PRT_ENDDATE) AS MAX_ENDDATE, COUNT(*) AS ROW_COUNT,
       COUNT(F_ANN_DATE) AS ANN_DATE_COUNT,
       COUNT(F_PRT_NETASSET) AS NETASSET_COUNT
FROM WDZX.CHINAMUTUALFUNDASSETPORTFOLIO
WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
GROUP BY S_INFO_WINDCODE;

-- Q08（limit=30）：ETF 单位净值、复权净值、复权因子和公告日小样本。
SELECT F_INFO_WINDCODE, PRICE_DATE, ANN_DATE, F_NAV_UNIT,
       F_NAV_ACCUMULATED, F_NAV_ADJFACTOR, F_NAV_ADJUSTED,
       F_PRT_NETASSET, NETASSET_TOTAL, IS_EXDIVIDENDDATE, OPDATE
FROM WDZX.CHINAMUTUALFUNDNAV
WHERE F_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
  AND PRICE_DATE BETWEEN '20260601' AND '20260605'
ORDER BY F_INFO_WINDCODE, PRICE_DATE;

-- Q09（limit=10）：3 只 ETF 的日净值范围和关键字段覆盖。
SELECT F_INFO_WINDCODE, MIN(PRICE_DATE) AS MIN_PRICE_DATE,
       MAX(PRICE_DATE) AS MAX_PRICE_DATE, COUNT(*) AS ROW_COUNT,
       COUNT(F_NAV_ADJUSTED) AS ADJUSTED_NAV_COUNT,
       COUNT(F_NAV_ADJFACTOR) AS ADJFACTOR_COUNT,
       COUNT(ANN_DATE) AS ANN_DATE_COUNT
FROM WDZX.CHINAMUTUALFUNDNAV
WHERE F_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
GROUP BY F_INFO_WINDCODE;

-- Q10（limit=30）：3 只 ETF 的开/收盘集合竞价价量、涨跌停小样本。
SELECT S_INFO_WINDCODE, TRADE_DT, DEALNUM_TOTAL,
       OPEN_AUCTION_PRICE, OPEN_AUCTION_VOLUME,
       CLOSE_AUCTION_PRICE, CLOSE_AUCTION_VOLUME,
       MAXUP, MAXDOWN
FROM WDZX.CHINACLOSEDFUNDAUCTION
WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
  AND TRADE_DT BETWEEN '20260601' AND '20260605'
ORDER BY S_INFO_WINDCODE, TRADE_DT;

-- Q11（limit=10）：3 只 ETF 的集合竞价历史范围和非空数量。
SELECT S_INFO_WINDCODE, MIN(TRADE_DT) AS MIN_TRADE_DT,
       MAX(TRADE_DT) AS MAX_TRADE_DT, COUNT(*) AS ROW_COUNT,
       COUNT(OPEN_AUCTION_PRICE) AS OPEN_PRICE_COUNT,
       COUNT(CLOSE_AUCTION_PRICE) AS CLOSE_PRICE_COUNT,
       COUNT(OPEN_AUCTION_VOLUME) AS OPEN_VOLUME_COUNT
FROM WDZX.CHINACLOSEDFUNDAUCTION
WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
GROUP BY S_INFO_WINDCODE;

-- Q12（limit=30）：基金停复牌事件样例。
SELECT S_INFO_WINDCODE, S_DQ_SUSPENDDATE, S_DQ_SUSPENDTIME,
       S_DQ_SUSPENDTYPE, S_DQ_RESUMPDATE, S_DQ_CHANGEREASON,
       S_DQ_CHANGEREASONTYPE, OPDATE
FROM WDZX.CMFTRADINGSUSPENSION
WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
ORDER BY S_INFO_WINDCODE, S_DQ_SUSPENDDATE;

-- Q13（limit=10）：沪深 300 价格指数和全收益指数的精确代码与口径。
SELECT S_INFO_WINDCODE, S_INFO_CODE, S_INFO_NAME, S_INFO_COMPNAME,
       S_INFO_EXCHMARKET, S_INFO_LISTDATE, EXPIRE_DATE,
       INCOME_PROCESSING_METHOD, S_INFO_PUBLISHER
FROM WDZX.AINDEXDESCRIPTION
WHERE S_INFO_WINDCODE IN ('000300.SH','h00300.CSI');

-- Q14（limit=10）：沪深 300 价格/全收益指数行情范围与开收盘覆盖。
SELECT S_INFO_WINDCODE,
       MIN(TRADE_DT) AS MIN_TRADE_DT,
       MAX(TRADE_DT) AS MAX_TRADE_DT,
       COUNT(*) AS ROW_COUNT,
       COUNT(S_DQ_CLOSE) AS CLOSE_COUNT,
       COUNT(S_DQ_OPEN) AS OPEN_COUNT,
       MAX(OPDATE) AS MAX_OPDATE
FROM WDZX.AINDEXEODPRICES
WHERE S_INFO_WINDCODE IN ('000300.SH','h00300.CSI')
GROUP BY S_INFO_WINDCODE;

-- Q15（limit=20）：验证指数涨跌幅字段是百分数而非小数。
SELECT S_INFO_WINDCODE, TRADE_DT, S_DQ_PRECLOSE, S_DQ_CLOSE,
       S_DQ_PCTCHANGE,
       ROUND((S_DQ_CLOSE / S_DQ_PRECLOSE - 1) * 100, 6) AS RECOMPUTED_PCT
FROM WDZX.AINDEXEODPRICES
WHERE S_INFO_WINDCODE IN ('000905.SH','000300.SH')
  AND TRADE_DT BETWEEN '20260528' AND '20260602'
ORDER BY S_INFO_WINDCODE, TRADE_DT;

-- Q16（limit=10）：3 只 ETF 复权净值与中证 500 在约三个月窗口的收益对齐。
WITH etf AS (
  SELECT F_INFO_WINDCODE, PRICE_DATE, F_NAV_ADJUSTED,
         LAG(F_NAV_ADJUSTED) OVER (
           PARTITION BY F_INFO_WINDCODE ORDER BY PRICE_DATE
         ) AS PREV_NAV
  FROM WDZX.CHINAMUTUALFUNDNAV
  WHERE F_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
    AND PRICE_DATE BETWEEN '20260220' AND '20260531'
),
idx AS (
  SELECT TRADE_DT, S_DQ_CLOSE,
         LAG(S_DQ_CLOSE) OVER (ORDER BY TRADE_DT) AS PREV_CLOSE
  FROM WDZX.AINDEXEODPRICES
  WHERE S_INFO_WINDCODE = '000905.SH'
    AND TRADE_DT BETWEEN '20260220' AND '20260531'
)
SELECT e.F_INFO_WINDCODE,
       COUNT(*) AS ALIGNED_DAYS,
       COUNT(CASE WHEN e.PREV_NAV IS NOT NULL AND i.PREV_CLOSE IS NOT NULL THEN 1 END) AS RETURN_PAIRS,
       MIN(e.PRICE_DATE) AS FIRST_ALIGNED_DT,
       MAX(e.PRICE_DATE) AS LAST_ALIGNED_DT
FROM etf e
JOIN idx i ON i.TRADE_DT = e.PRICE_DATE
WHERE e.PRICE_DATE BETWEEN '20260301' AND '20260531'
GROUP BY e.F_INFO_WINDCODE;

-- Q17（limit=5）：中证 500 与沪深 300 在同一窗口的收益对齐。
WITH p AS (
  SELECT S_INFO_WINDCODE, TRADE_DT, S_DQ_CLOSE,
         LAG(S_DQ_CLOSE) OVER (
           PARTITION BY S_INFO_WINDCODE ORDER BY TRADE_DT
         ) AS PREV_CLOSE
  FROM WDZX.AINDEXEODPRICES
  WHERE S_INFO_WINDCODE IN ('000905.SH','000300.SH')
    AND TRADE_DT BETWEEN '20260220' AND '20260531'
)
SELECT COUNT(*) AS ALIGNED_DAYS,
       COUNT(CASE WHEN i.PREV_CLOSE IS NOT NULL AND b.PREV_CLOSE IS NOT NULL THEN 1 END) AS RETURN_PAIRS,
       MIN(i.TRADE_DT) AS FIRST_ALIGNED_DT,
       MAX(i.TRADE_DT) AS LAST_ALIGNED_DT
FROM p i
JOIN p b ON b.TRADE_DT = i.TRADE_DT
WHERE i.S_INFO_WINDCODE = '000905.SH'
  AND b.S_INFO_WINDCODE = '000300.SH'
  AND i.TRADE_DT BETWEEN '20260301' AND '20260531';

-- Q18（limit=10）：约 16 个月的沪深 300 月末数据计算 MA3、MA12、S3、S12。
WITH ranked AS (
  SELECT TRADE_DT, S_DQ_CLOSE, SUBSTR(TRADE_DT,1,6) AS YM,
         ROW_NUMBER() OVER (
           PARTITION BY SUBSTR(TRADE_DT,1,6) ORDER BY TRADE_DT DESC
         ) AS RN
  FROM WDZX.AINDEXEODPRICES
  WHERE S_INFO_WINDCODE = '000300.SH'
    AND TRADE_DT BETWEEN '20250501' AND '20260831'
),
monthly AS (
  SELECT TRADE_DT, YM, S_DQ_CLOSE
  FROM ranked
  WHERE RN = 1
),
ma AS (
  SELECT TRADE_DT, YM, S_DQ_CLOSE,
         AVG(S_DQ_CLOSE) OVER (ORDER BY YM ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MA3,
         AVG(S_DQ_CLOSE) OVER (ORDER BY YM ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS MA12,
         COUNT(*) OVER (ORDER BY YM ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS MA12_OBS
  FROM monthly
),
slopes AS (
  SELECT TRADE_DT, YM, S_DQ_CLOSE, MA3, MA12, MA12_OBS,
         MA3 / LAG(MA3) OVER (ORDER BY YM) - 1 AS S3,
         MA12 / LAG(MA12) OVER (ORDER BY YM) - 1 AS S12
  FROM ma
)
SELECT TRADE_DT, YM, S_DQ_CLOSE, MA3, MA12, MA12_OBS, S3, S12
FROM slopes
WHERE YM IN ('202607','202608')
ORDER BY YM;

-- Q19（limit=20）：SSE 小窗口交易日及下一交易日。
SELECT TRADE_DAYS,
       LEAD(TRADE_DAYS) OVER (ORDER BY TRADE_DAYS) AS NEXT_TRADE_DAY
FROM WDZX.ASHARECALENDAR
WHERE S_INFO_EXCHMARKET = 'SSE'
  AND TRADE_DAYS BETWEEN '20260529' AND '20260610'
ORDER BY TRADE_DAYS;

-- Q20（limit=10）：已退市 ETF 515930.SH 在净值、规模和竞价表中的保留范围。
SELECT 'NAV' AS SOURCE_NAME,
       MIN(PRICE_DATE) AS MIN_DT, MAX(PRICE_DATE) AS MAX_DT,
       COUNT(*) AS ROW_COUNT
FROM WDZX.CHINAMUTUALFUNDNAV
WHERE F_INFO_WINDCODE = '515930.SH'
UNION ALL
SELECT 'ASSET_PORTFOLIO',
       MIN(F_PRT_ENDDATE), MAX(F_PRT_ENDDATE), COUNT(*)
FROM WDZX.CHINAMUTUALFUNDASSETPORTFOLIO
WHERE S_INFO_WINDCODE = '515930.SH'
UNION ALL
SELECT 'AUCTION',
       MIN(TRADE_DT), MAX(TRADE_DT), COUNT(*)
FROM WDZX.CHINACLOSEDFUNDAUCTION
WHERE S_INFO_WINDCODE = '515930.SH';

-- Q21（limit=20）：受限窗口逻辑键重复检查；成功执行并返回 0 行。
SELECT SOURCE_NAME, CODE, BUSINESS_DT, DUP_COUNT
FROM (
  SELECT 'NAV' AS SOURCE_NAME, F_INFO_WINDCODE AS CODE,
         PRICE_DATE AS BUSINESS_DT, COUNT(*) AS DUP_COUNT
  FROM WDZX.CHINAMUTUALFUNDNAV
  WHERE F_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
    AND PRICE_DATE BETWEEN '20260301' AND '20260531'
  GROUP BY F_INFO_WINDCODE, PRICE_DATE
  HAVING COUNT(*) > 1
  UNION ALL
  SELECT 'INDEX_EOD', S_INFO_WINDCODE, TRADE_DT, COUNT(*)
  FROM WDZX.AINDEXEODPRICES
  WHERE S_INFO_WINDCODE IN ('000905.SH','000300.SH')
    AND TRADE_DT BETWEEN '20260301' AND '20260531'
  GROUP BY S_INFO_WINDCODE, TRADE_DT
  HAVING COUNT(*) > 1
  UNION ALL
  SELECT 'AUCTION', S_INFO_WINDCODE, TRADE_DT, COUNT(*)
  FROM WDZX.CHINACLOSEDFUNDAUCTION
  WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
    AND TRADE_DT BETWEEN '20260301' AND '20260531'
  GROUP BY S_INFO_WINDCODE, TRADE_DT
  HAVING COUNT(*) > 1
);

-- Q22（limit=10）：证伪 ASHAREEODPRICES 可用于样例 ETF；成功执行并返回 0 行。
SELECT S_INFO_WINDCODE, MIN(TRADE_DT) AS MIN_TRADE_DT,
       MAX(TRADE_DT) AS MAX_TRADE_DT, COUNT(*) AS ROW_COUNT
FROM WDZX.ASHAREEODPRICES
WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH','510300.SH')
GROUP BY S_INFO_WINDCODE;

-- Q23（limit=30）：候选表的统计行数和统计更新时间，避免大表全扫描。
SELECT TABLE_NAME, NUM_ROWS, LAST_ANALYZED
FROM ALL_TABLES
WHERE OWNER = 'WDZX'
  AND TABLE_NAME IN (
    'CHINAMUTUALFUNDDESCRIPTION',
    'CHINAETFINVESTCLASS',
    'CHINAMUTUALFUNDSECTOR',
    'CHINAMUTUALFUNDTRACKINGINDEX',
    'CHINAMUTUALFUNDBENCHMARK',
    'CHINAMUTUALFUNDNAV',
    'CHINAMUTUALFUNDASSETPORTFOLIO',
    'AINDEXDESCRIPTION',
    'AINDEXEODPRICES',
    'ASHARECALENDAR',
    'CHINACLOSEDFUNDAUCTION',
    'CMFTRADINGSUSPENSION',
    'CHINAMFDIVIDEND',
    'CMFUNDSPLIT',
    'ASHAREEODPRICES'
  )
ORDER BY TABLE_NAME;

-- Q24（limit=20）：历史基金/场内证券代码变更样例。
SELECT S_INFO_WINDCODE, S_INFO_OLDWINDCODE,
       S_INFO_NEWWINDCODE, CHANGE_DATE, OPDATE
FROM WDZX.CFUNDCHANGEWINDCODE
WHERE S_INFO_OLDWINDCODE LIKE '%.SH'
   OR S_INFO_OLDWINDCODE LIKE '%.SZ'
   OR S_INFO_NEWWINDCODE LIKE '%.SH'
   OR S_INFO_NEWWINDCODE LIKE '%.SZ'
ORDER BY CHANGE_DATE DESC;

-- Q25（limit=30）：样例 ETF 的拆分/折算公告、实施和比例。
SELECT S_INFO_WINDCODE, F_INFO_SPLITTYPE, F_INFO_SPLITANNDATE,
       F_INFO_SPLITANNOECDATE, F_INFO_SHARETRANSDATE,
       F_INFO_SHAREKINDATE, F_INFO_SPLITINC, F_INFO_SPLIT_DT, OPDATE
FROM WDZX.CMFUNDSPLIT
WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
ORDER BY S_INFO_WINDCODE, F_INFO_SHARETRANSDATE;

-- Q26（limit=30）：样例 ETF 的现金分红公告、登记、除息和派息。
SELECT S_INFO_WINDCODE, ANN_DATE, F_DIV_IMPDATE, EQY_RECORD_DT,
       EX_DT, PAY_DT, CASH_DVD_PER_SH_TAX, CRNCY_CODE, OPDATE
FROM WDZX.CHINAMFDIVIDEND
WHERE S_INFO_WINDCODE IN ('510300.SH','510500.SH','510510.SH','512500.SH')
ORDER BY S_INFO_WINDCODE, EX_DT;

-- Q27（limit=5）：确认受限简化版暂定起始月的首个 SSE 交易日。
SELECT MIN(TRADE_DAYS) AS FIRST_TRADE_DAY
FROM WDZX.ASHARECALENDAR
WHERE S_INFO_EXCHMARKET = 'SSE'
  AND TRADE_DAYS BETWEEN '20190801' AND '20190831';
