-- WDZX Oracle 数据库可行性审计：实际成功执行的只读证据 SQL
-- 初审日期：2026-09-16；阶段 0.5 终审更新：2026-09-17
-- 所有语句均通过 oracle_wdzx.execute_select 单独执行；MCP 调用时不带末尾分号。
-- 语句后的“limit”写在注释中，实际分页由 MCP 强制施加。
-- 不含任何连接串、密码、DDL、DML、存储过程或 EXPLAIN PLAN。

-- Q01（limit=5）：当前已上市有效 ETF 候选及审计日开/收盘集合竞价可成交数量。
WITH etf AS (
  SELECT DISTINCT c.S_INFO_WINDCODE
  FROM WDZX.CHINAETFINVESTCLASS c
  JOIN WDZX.CHINAMUTUALFUNDDESCRIPTION d
    ON d.F_INFO_WINDCODE = c.S_INFO_WINDCODE
  WHERE d.LISTEDFUNDORNOT = 1
    AND d.F_INFO_STATUS = 101001000
    AND d.F_INFO_LISTDATE <= '20260916'
    AND (d.F_INFO_DELISTDATE IS NULL OR d.F_INFO_DELISTDATE > '20260916')
    AND (c.S_INFO_WINDCODE LIKE '%.SH' OR c.S_INFO_WINDCODE LIKE '%.SZ')
)
SELECT COUNT(*) AS IDENTIFIED_LIVE_ETFS,
       COUNT(a.S_INFO_WINDCODE) AS WITH_AUCTION_ROW,
       COUNT(CASE WHEN a.OPEN_AUCTION_PRICE > 0 AND a.OPEN_AUCTION_VOLUME > 0 THEN 1 END) AS WITH_VALID_OPEN_AUCTION,
       COUNT(CASE WHEN a.CLOSE_AUCTION_PRICE > 0 AND a.CLOSE_AUCTION_VOLUME > 0 THEN 1 END) AS WITH_VALID_CLOSE_AUCTION
FROM etf e
LEFT JOIN WDZX.CHINACLOSEDFUNDAUCTION a
  ON a.S_INFO_WINDCODE = e.S_INFO_WINDCODE
 AND a.TRADE_DT = '20260916';

-- Q02（limit=5）：按 2023-06-01 生效区间重建 ETF 池，并验证包含后来退市的 515930.SH。
SELECT COUNT(DISTINCT s.F_INFO_WINDCODE) AS ETF_COUNT_AT_DATE,
       MAX(CASE WHEN s.F_INFO_WINDCODE = '515930.SH' THEN 1 ELSE 0 END) AS INCLUDES_LATER_DELISTED_ETF
FROM WDZX.CHINAMUTUALFUNDSECTOR s
JOIN WDZX.CHINAMUTUALFUNDDESCRIPTION d
  ON d.F_INFO_WINDCODE = s.F_INFO_WINDCODE
WHERE s.S_INFO_SECTOR = '2001020200'
  AND s.S_INFO_SECTORENTRYDT <= '20230601'
  AND (s.S_INFO_SECTOREXITDT IS NULL OR s.S_INFO_SECTOREXITDT > '20230601')
  AND d.F_INFO_LISTDATE <= '20230601'
  AND (d.F_INFO_DELISTDATE IS NULL OR d.F_INFO_DELISTDATE > '20230601')
  AND d.LISTEDFUNDORNOT = 1;

-- Q03（limit=50）：跟踪指数映射的生效/失效样例，包括已退市 ETF。
SELECT S_INFO_WINDCODE, S_INFO_INDEXWINDCODE, ENTRY_DT, REMOVE_DT, OPDATE, OPMODE
FROM WDZX.CHINAMUTUALFUNDTRACKINGINDEX
WHERE S_INFO_WINDCODE IN ('510300.SH','510310.SH','159919.SZ','159925.SZ','515930.SH')
ORDER BY S_INFO_WINDCODE, ENTRY_DT;

-- Q04（limit=5）：跟踪指数映射表的日期和字段覆盖。
SELECT COUNT(*) AS MAPPING_ROWS,
       COUNT(CASE WHEN ENTRY_DT IS NOT NULL THEN 1 END) AS WITH_ENTRY_DT,
       COUNT(CASE WHEN REMOVE_DT IS NOT NULL THEN 1 END) AS WITH_REMOVE_DT,
       COUNT(CASE WHEN S_INFO_INDEXWINDCODE IS NOT NULL THEN 1 END) AS WITH_INDEX_CODE,
       MIN(ENTRY_DT) AS MIN_ENTRY_DT,
       MAX(ENTRY_DT) AS MAX_ENTRY_DT,
       MAX(OPDATE) AS MAX_OPDATE
FROM WDZX.CHINAMUTUALFUNDTRACKINGINDEX
WHERE S_INFO_WINDCODE IS NOT NULL;

-- Q05（limit=50）：3 只中证 500 ETF 的业绩基准、权重、有效期和公告日。
SELECT S_INFO_WINDCODE, S_INFO_INDEXWINDCODE, S_INFO_BGNDT,
       S_INFO_ENDDT, S_INFO_INDEXWEG, CUR_SIGN, ANN_DT, S_INC_SEQUENCE
FROM WDZX.CHINAMUTUALFUNDBENCHMARK
WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
ORDER BY S_INFO_WINDCODE, S_INFO_BGNDT, S_INC_SEQUENCE;

-- Q06（limit=50）：3 只 ETF 的历史规模报告期与公告日样例。
SELECT S_INFO_WINDCODE, S_INFO_INNERCODE, S_INFO_OUTERCODE,
       F_PRT_ENDDATE, F_ANN_DATE, F_PRT_TOTALASSET, F_PRT_NETASSET,
       CRNCY_CODE, OPDATE
FROM WDZX.CHINAMUTUALFUNDASSETPORTFOLIO
WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
  AND F_PRT_ENDDATE BETWEEN '20241231' AND '20251231'
ORDER BY S_INFO_WINDCODE, F_PRT_ENDDATE;

-- Q07（limit=10）：3 只 ETF 的规模历史范围和公告日覆盖。
SELECT S_INFO_WINDCODE, MIN(F_PRT_ENDDATE) AS MIN_ENDDATE,
       MAX(F_PRT_ENDDATE) AS MAX_ENDDATE, COUNT(*) AS ROW_COUNT,
       COUNT(F_ANN_DATE) AS ANN_DATE_COUNT,
       COUNT(F_PRT_NETASSET) AS NETASSET_COUNT
FROM WDZX.CHINAMUTUALFUNDASSETPORTFOLIO
WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
GROUP BY S_INFO_WINDCODE;

-- Q08（limit=30）：ETF 单位净值、复权净值、复权因子和公告日小样本。
SELECT F_INFO_WINDCODE, PRICE_DATE, ANN_DATE, F_NAV_UNIT,
       F_NAV_ACCUMULATED, F_NAV_ADJFACTOR, F_NAV_ADJUSTED,
       F_PRT_NETASSET, NETASSET_TOTAL, IS_EXDIVIDENDDATE, OPDATE
FROM WDZX.CHINAMUTUALFUNDNAV
WHERE F_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
  AND PRICE_DATE BETWEEN '20260601' AND '20260605'
ORDER BY F_INFO_WINDCODE, PRICE_DATE;

-- Q09（limit=10）：3 只 ETF 的日净值范围和关键字段覆盖。
SELECT F_INFO_WINDCODE, MIN(PRICE_DATE) AS MIN_PRICE_DATE,
       MAX(PRICE_DATE) AS MAX_PRICE_DATE, COUNT(*) AS ROW_COUNT,
       COUNT(F_NAV_ADJUSTED) AS ADJUSTED_NAV_COUNT,
       COUNT(F_NAV_ADJFACTOR) AS ADJFACTOR_COUNT,
       COUNT(ANN_DATE) AS ANN_DATE_COUNT
FROM WDZX.CHINAMUTUALFUNDNAV
WHERE F_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
GROUP BY F_INFO_WINDCODE;

-- Q10（limit=30）：3 只 ETF 的开/收盘集合竞价价量、涨跌停小样本。
SELECT S_INFO_WINDCODE, TRADE_DT, DEALNUM_TOTAL,
       OPEN_AUCTION_PRICE, OPEN_AUCTION_VOLUME,
       CLOSE_AUCTION_PRICE, CLOSE_AUCTION_VOLUME,
       MAXUP, MAXDOWN
FROM WDZX.CHINACLOSEDFUNDAUCTION
WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
  AND TRADE_DT BETWEEN '20260601' AND '20260605'
ORDER BY S_INFO_WINDCODE, TRADE_DT;

-- Q11（limit=10）：3 只 ETF 的集合竞价历史范围和非空数量。
SELECT S_INFO_WINDCODE, MIN(TRADE_DT) AS MIN_TRADE_DT,
       MAX(TRADE_DT) AS MAX_TRADE_DT, COUNT(*) AS ROW_COUNT,
       COUNT(OPEN_AUCTION_PRICE) AS OPEN_PRICE_COUNT,
       COUNT(CLOSE_AUCTION_PRICE) AS CLOSE_PRICE_COUNT,
       COUNT(OPEN_AUCTION_VOLUME) AS OPEN_VOLUME_COUNT
FROM WDZX.CHINACLOSEDFUNDAUCTION
WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
GROUP BY S_INFO_WINDCODE;

-- Q12（limit=30）：基金停复牌事件样例。
SELECT S_INFO_WINDCODE, S_DQ_SUSPENDDATE, S_DQ_SUSPENDTIME,
       S_DQ_SUSPENDTYPE, S_DQ_RESUMPDATE, S_DQ_CHANGEREASON,
       S_DQ_CHANGEREASONTYPE, OPDATE
FROM WDZX.CMFTRADINGSUSPENSION
WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
ORDER BY S_INFO_WINDCODE, S_DQ_SUSPENDDATE;

-- Q13（limit=10）：沪深 300 价格指数和全收益指数的精确代码与口径。
SELECT S_INFO_WINDCODE, S_INFO_CODE, S_INFO_NAME, S_INFO_COMPNAME,
       S_INFO_EXCHMARKET, S_INFO_LISTDATE, EXPIRE_DATE,
       INCOME_PROCESSING_METHOD, S_INFO_PUBLISHER
FROM WDZX.AINDEXDESCRIPTION
WHERE S_INFO_WINDCODE IN ('000300.SH','h00300.CSI');

-- Q14（limit=10）：沪深 300 价格/全收益指数行情范围与开收盘覆盖。
SELECT S_INFO_WINDCODE,
       MIN(TRADE_DT) AS MIN_TRADE_DT,
       MAX(TRADE_DT) AS MAX_TRADE_DT,
       COUNT(*) AS ROW_COUNT,
       COUNT(S_DQ_CLOSE) AS CLOSE_COUNT,
       COUNT(S_DQ_OPEN) AS OPEN_COUNT,
       MAX(OPDATE) AS MAX_OPDATE
FROM WDZX.AINDEXEODPRICES
WHERE S_INFO_WINDCODE IN ('000300.SH','h00300.CSI')
GROUP BY S_INFO_WINDCODE;

-- Q15（limit=20）：验证指数涨跌幅字段是百分数而非小数。
SELECT S_INFO_WINDCODE, TRADE_DT, S_DQ_PRECLOSE, S_DQ_CLOSE,
       S_DQ_PCTCHANGE,
       ROUND((S_DQ_CLOSE / S_DQ_PRECLOSE - 1) * 100, 6) AS RECOMPUTED_PCT
FROM WDZX.AINDEXEODPRICES
WHERE S_INFO_WINDCODE IN ('000905.SH','000300.SH')
  AND TRADE_DT BETWEEN '20260528' AND '20260602'
ORDER BY S_INFO_WINDCODE, TRADE_DT;

-- Q16（limit=10）：3 只 ETF 复权净值与中证 500 在约三个月窗口的收益对齐。
WITH etf AS (
  SELECT F_INFO_WINDCODE, PRICE_DATE, F_NAV_ADJUSTED,
         LAG(F_NAV_ADJUSTED) OVER (
           PARTITION BY F_INFO_WINDCODE ORDER BY PRICE_DATE
         ) AS PREV_NAV
  FROM WDZX.CHINAMUTUALFUNDNAV
  WHERE F_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
    AND PRICE_DATE BETWEEN '20260220' AND '20260531'
),
idx AS (
  SELECT TRADE_DT, S_DQ_CLOSE,
         LAG(S_DQ_CLOSE) OVER (ORDER BY TRADE_DT) AS PREV_CLOSE
  FROM WDZX.AINDEXEODPRICES
  WHERE S_INFO_WINDCODE = '000905.SH'
    AND TRADE_DT BETWEEN '20260220' AND '20260531'
)
SELECT e.F_INFO_WINDCODE,
       COUNT(*) AS ALIGNED_DAYS,
       COUNT(CASE WHEN e.PREV_NAV IS NOT NULL AND i.PREV_CLOSE IS NOT NULL THEN 1 END) AS RETURN_PAIRS,
       MIN(e.PRICE_DATE) AS FIRST_ALIGNED_DT,
       MAX(e.PRICE_DATE) AS LAST_ALIGNED_DT
FROM etf e
JOIN idx i ON i.TRADE_DT = e.PRICE_DATE
WHERE e.PRICE_DATE BETWEEN '20260301' AND '20260531'
GROUP BY e.F_INFO_WINDCODE;

-- Q17（limit=5）：中证 500 与沪深 300 在同一窗口的收益对齐。
WITH p AS (
  SELECT S_INFO_WINDCODE, TRADE_DT, S_DQ_CLOSE,
         LAG(S_DQ_CLOSE) OVER (
           PARTITION BY S_INFO_WINDCODE ORDER BY TRADE_DT
         ) AS PREV_CLOSE
  FROM WDZX.AINDEXEODPRICES
  WHERE S_INFO_WINDCODE IN ('000905.SH','000300.SH')
    AND TRADE_DT BETWEEN '20260220' AND '20260531'
)
SELECT COUNT(*) AS ALIGNED_DAYS,
       COUNT(CASE WHEN i.PREV_CLOSE IS NOT NULL AND b.PREV_CLOSE IS NOT NULL THEN 1 END) AS RETURN_PAIRS,
       MIN(i.TRADE_DT) AS FIRST_ALIGNED_DT,
       MAX(i.TRADE_DT) AS LAST_ALIGNED_DT
FROM p i
JOIN p b ON b.TRADE_DT = i.TRADE_DT
WHERE i.S_INFO_WINDCODE = '000905.SH'
  AND b.S_INFO_WINDCODE = '000300.SH'
  AND i.TRADE_DT BETWEEN '20260301' AND '20260531';

-- Q18（limit=10）：约 16 个月的沪深 300 月末数据计算 MA3、MA12、S3、S12。
WITH ranked AS (
  SELECT TRADE_DT, S_DQ_CLOSE, SUBSTR(TRADE_DT,1,6) AS YM,
         ROW_NUMBER() OVER (
           PARTITION BY SUBSTR(TRADE_DT,1,6) ORDER BY TRADE_DT DESC
         ) AS RN
  FROM WDZX.AINDEXEODPRICES
  WHERE S_INFO_WINDCODE = '000300.SH'
    AND TRADE_DT BETWEEN '20250501' AND '20260831'
),
monthly AS (
  SELECT TRADE_DT, YM, S_DQ_CLOSE
  FROM ranked
  WHERE RN = 1
),
ma AS (
  SELECT TRADE_DT, YM, S_DQ_CLOSE,
         AVG(S_DQ_CLOSE) OVER (ORDER BY YM ROWS BETWEEN 2 PRECEDING AND CURRENT ROW) AS MA3,
         AVG(S_DQ_CLOSE) OVER (ORDER BY YM ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS MA12,
         COUNT(*) OVER (ORDER BY YM ROWS BETWEEN 11 PRECEDING AND CURRENT ROW) AS MA12_OBS
  FROM monthly
),
slopes AS (
  SELECT TRADE_DT, YM, S_DQ_CLOSE, MA3, MA12, MA12_OBS,
         MA3 / LAG(MA3) OVER (ORDER BY YM) - 1 AS S3,
         MA12 / LAG(MA12) OVER (ORDER BY YM) - 1 AS S12
  FROM ma
)
SELECT TRADE_DT, YM, S_DQ_CLOSE, MA3, MA12, MA12_OBS, S3, S12
FROM slopes
WHERE YM IN ('202607','202608')
ORDER BY YM;

-- Q19（limit=20）：SSE 小窗口交易日及下一交易日。
SELECT TRADE_DAYS,
       LEAD(TRADE_DAYS) OVER (ORDER BY TRADE_DAYS) AS NEXT_TRADE_DAY
FROM WDZX.ASHARECALENDAR
WHERE S_INFO_EXCHMARKET = 'SSE'
  AND TRADE_DAYS BETWEEN '20260529' AND '20260610'
ORDER BY TRADE_DAYS;

-- Q20（limit=10）：已退市 ETF 515930.SH 在净值、规模和竞价表中的保留范围。
SELECT 'NAV' AS SOURCE_NAME,
       MIN(PRICE_DATE) AS MIN_DT, MAX(PRICE_DATE) AS MAX_DT,
       COUNT(*) AS ROW_COUNT
FROM WDZX.CHINAMUTUALFUNDNAV
WHERE F_INFO_WINDCODE = '515930.SH'
UNION ALL
SELECT 'ASSET_PORTFOLIO',
       MIN(F_PRT_ENDDATE), MAX(F_PRT_ENDDATE), COUNT(*)
FROM WDZX.CHINAMUTUALFUNDASSETPORTFOLIO
WHERE S_INFO_WINDCODE = '515930.SH'
UNION ALL
SELECT 'AUCTION',
       MIN(TRADE_DT), MAX(TRADE_DT), COUNT(*)
FROM WDZX.CHINACLOSEDFUNDAUCTION
WHERE S_INFO_WINDCODE = '515930.SH';

-- Q21（limit=20）：受限窗口逻辑键重复检查；成功执行并返回 0 行。
SELECT SOURCE_NAME, CODE, BUSINESS_DT, DUP_COUNT
FROM (
  SELECT 'NAV' AS SOURCE_NAME, F_INFO_WINDCODE AS CODE,
         PRICE_DATE AS BUSINESS_DT, COUNT(*) AS DUP_COUNT
  FROM WDZX.CHINAMUTUALFUNDNAV
  WHERE F_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
    AND PRICE_DATE BETWEEN '20260301' AND '20260531'
  GROUP BY F_INFO_WINDCODE, PRICE_DATE
  HAVING COUNT(*) > 1
  UNION ALL
  SELECT 'INDEX_EOD', S_INFO_WINDCODE, TRADE_DT, COUNT(*)
  FROM WDZX.AINDEXEODPRICES
  WHERE S_INFO_WINDCODE IN ('000905.SH','000300.SH')
    AND TRADE_DT BETWEEN '20260301' AND '20260531'
  GROUP BY S_INFO_WINDCODE, TRADE_DT
  HAVING COUNT(*) > 1
  UNION ALL
  SELECT 'AUCTION', S_INFO_WINDCODE, TRADE_DT, COUNT(*)
  FROM WDZX.CHINACLOSEDFUNDAUCTION
  WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
    AND TRADE_DT BETWEEN '20260301' AND '20260531'
  GROUP BY S_INFO_WINDCODE, TRADE_DT
  HAVING COUNT(*) > 1
);

-- Q22（limit=10）：证伪 ASHAREEODPRICES 可用于样例 ETF；成功执行并返回 0 行。
SELECT S_INFO_WINDCODE, MIN(TRADE_DT) AS MIN_TRADE_DT,
       MAX(TRADE_DT) AS MAX_TRADE_DT, COUNT(*) AS ROW_COUNT
FROM WDZX.ASHAREEODPRICES
WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH','510300.SH')
GROUP BY S_INFO_WINDCODE;

-- Q23（limit=30）：候选表的统计行数和统计更新时间，避免大表全扫描。
SELECT TABLE_NAME, NUM_ROWS, LAST_ANALYZED
FROM ALL_TABLES
WHERE OWNER = 'WDZX'
  AND TABLE_NAME IN (
    'CHINAMUTUALFUNDDESCRIPTION',
    'CHINAETFINVESTCLASS',
    'CHINAMUTUALFUNDSECTOR',
    'CHINAMUTUALFUNDTRACKINGINDEX',
    'CHINAMUTUALFUNDBENCHMARK',
    'CHINAMUTUALFUNDNAV',
    'CHINAMUTUALFUNDASSETPORTFOLIO',
    'AINDEXDESCRIPTION',
    'AINDEXEODPRICES',
    'ASHARECALENDAR',
    'CHINACLOSEDFUNDAUCTION',
    'CMFTRADINGSUSPENSION',
    'CHINAMFDIVIDEND',
    'CMFUNDSPLIT',
    'ASHAREEODPRICES'
  )
ORDER BY TABLE_NAME;

-- Q24（limit=20）：历史基金/场内证券代码变更样例。
SELECT S_INFO_WINDCODE, S_INFO_OLDWINDCODE,
       S_INFO_NEWWINDCODE, CHANGE_DATE, OPDATE
FROM WDZX.CFUNDCHANGEWINDCODE
WHERE S_INFO_OLDWINDCODE LIKE '%.SH'
   OR S_INFO_OLDWINDCODE LIKE '%.SZ'
   OR S_INFO_NEWWINDCODE LIKE '%.SH'
   OR S_INFO_NEWWINDCODE LIKE '%.SZ'
ORDER BY CHANGE_DATE DESC;

-- Q25（limit=30）：样例 ETF 的拆分/折算公告、实施和比例。
SELECT S_INFO_WINDCODE, F_INFO_SPLITTYPE, F_INFO_SPLITANNDATE,
       F_INFO_SPLITANNOECDATE, F_INFO_SHARETRANSDATE,
       F_INFO_SHAREKINDATE, F_INFO_SPLITINC, F_INFO_SPLIT_DT, OPDATE
FROM WDZX.CMFUNDSPLIT
WHERE S_INFO_WINDCODE IN ('510500.SH','510510.SH','512500.SH')
ORDER BY S_INFO_WINDCODE, F_INFO_SHARETRANSDATE;

-- Q26（limit=30）：样例 ETF 的现金分红公告、登记、除息和派息。
SELECT S_INFO_WINDCODE, ANN_DATE, F_DIV_IMPDATE, EQY_RECORD_DT,
       EX_DT, PAY_DT, CASH_DVD_PER_SH_TAX, CRNCY_CODE, OPDATE
FROM WDZX.CHINAMFDIVIDEND
WHERE S_INFO_WINDCODE IN ('510300.SH','510500.SH','510510.SH','512500.SH')
ORDER BY S_INFO_WINDCODE, EX_DT;

-- Q27（limit=5）：确认受限简化版暂定起始月的首个 SSE 交易日。
SELECT MIN(TRADE_DAYS) AS FIRST_TRADE_DAY
FROM WDZX.ASHARECALENDAR
WHERE S_INFO_EXCHMARKET = 'SSE'
  AND TRADE_DAYS BETWEEN '20190801' AND '20190831';

-- Q28（limit=50）：按表聚合代码、日期、OHLC、复权、量额、交易状态和净值字段能力。
WITH col_caps AS (
  SELECT c.OWNER, c.TABLE_NAME, c.COLUMN_NAME,
         NVL(cc.COMMENTS, '') AS COLUMN_COMMENT,
         CASE WHEN c.COLUMN_NAME IN
              ('S_INFO_WINDCODE','F_INFO_WINDCODE','SEC_ID','WINDCODE','S_INFO_CODE')
              THEN 1 ELSE 0 END AS HAS_CODE,
         CASE WHEN c.COLUMN_NAME IN
              ('TRADE_DT','PRICE_DATE','TRADE_DATE','S_DQ_DATE','TRADE_DAYS')
              THEN 1 ELSE 0 END AS HAS_TRADE_DATE,
         CASE WHEN c.COLUMN_NAME IN
              ('S_DQ_OPEN','OPEN_PRICE','OPEN_AUCTION_PRICE','F_DQ_OPEN')
              OR INSTR(NVL(cc.COMMENTS, ''), '开盘价') > 0
              THEN 1 ELSE 0 END AS HAS_OPEN,
         CASE WHEN c.COLUMN_NAME IN
              ('S_DQ_CLOSE','CLOSE_PRICE','CLOSE_AUCTION_PRICE','F_DQ_CLOSE')
              OR INSTR(NVL(cc.COMMENTS, ''), '收盘价') > 0
              THEN 1 ELSE 0 END AS HAS_CLOSE,
         CASE WHEN c.COLUMN_NAME IN ('S_DQ_PRECLOSE','PRECLOSE','PRE_CLOSE')
              OR INSTR(NVL(cc.COMMENTS, ''), '前收盘') > 0
              THEN 1 ELSE 0 END AS HAS_PRECLOSE,
         CASE WHEN REGEXP_LIKE(c.COLUMN_NAME, 'ADJ(OPEN|CLOSE|FACTOR)|ADJUSTED')
              OR INSTR(NVL(cc.COMMENTS, ''), '复权') > 0
              THEN 1 ELSE 0 END AS HAS_ADJUST,
         CASE WHEN REGEXP_LIKE(c.COLUMN_NAME, '(^|_)(VOLUME|VOL)($|_)')
              OR INSTR(NVL(cc.COMMENTS, ''), '成交量') > 0
              THEN 1 ELSE 0 END AS HAS_VOLUME,
         CASE WHEN REGEXP_LIKE(c.COLUMN_NAME, '(^|_)(AMOUNT|AMT)($|_)')
              OR INSTR(NVL(cc.COMMENTS, ''), '成交额') > 0
              THEN 1 ELSE 0 END AS HAS_AMOUNT,
         CASE WHEN REGEXP_LIKE(c.COLUMN_NAME, 'TRADESTATUS|SUSPEND|STOPPING|MAXUP|MAXDOWN|LIMIT')
              OR REGEXP_LIKE(NVL(cc.COMMENTS, ''), '停牌|交易状态|涨停|跌停')
              THEN 1 ELSE 0 END AS HAS_TRADE_STATE,
         CASE WHEN REGEXP_LIKE(c.COLUMN_NAME, 'NAV|IOPV')
              OR REGEXP_LIKE(NVL(cc.COMMENTS, ''), '净值|IOPV')
              THEN 1 ELSE 0 END AS HAS_NAV
  FROM ALL_TAB_COLUMNS c
  LEFT JOIN ALL_COL_COMMENTS cc
    ON cc.OWNER = c.OWNER
   AND cc.TABLE_NAME = c.TABLE_NAME
   AND cc.COLUMN_NAME = c.COLUMN_NAME
  WHERE c.OWNER = 'WDZX'
), table_caps AS (
  SELECT OWNER, TABLE_NAME,
         MAX(HAS_CODE) AS HAS_CODE,
         MAX(HAS_TRADE_DATE) AS HAS_TRADE_DATE,
         MAX(HAS_OPEN) AS HAS_OPEN,
         MAX(HAS_CLOSE) AS HAS_CLOSE,
         MAX(HAS_PRECLOSE) AS HAS_PRECLOSE,
         MAX(HAS_ADJUST) AS HAS_ADJUST,
         MAX(HAS_VOLUME) AS HAS_VOLUME,
         MAX(HAS_AMOUNT) AS HAS_AMOUNT,
         MAX(HAS_TRADE_STATE) AS HAS_TRADE_STATE,
         MAX(HAS_NAV) AS HAS_NAV
  FROM col_caps
  GROUP BY OWNER, TABLE_NAME
)
SELECT t.TABLE_NAME, o.OBJECT_TYPE, tc.COMMENTS AS TABLE_COMMENT,
       t.HAS_CODE, t.HAS_TRADE_DATE, t.HAS_OPEN, t.HAS_CLOSE,
       t.HAS_PRECLOSE, t.HAS_ADJUST, t.HAS_VOLUME, t.HAS_AMOUNT,
       t.HAS_TRADE_STATE, t.HAS_NAV,
       (t.HAS_CODE + t.HAS_TRADE_DATE + t.HAS_OPEN + t.HAS_CLOSE +
        t.HAS_PRECLOSE + t.HAS_ADJUST + t.HAS_VOLUME + t.HAS_AMOUNT +
        t.HAS_TRADE_STATE) AS MARKET_CAPABILITY_SCORE
FROM table_caps t
JOIN ALL_OBJECTS o
  ON o.OWNER = t.OWNER
 AND o.OBJECT_NAME = t.TABLE_NAME
LEFT JOIN ALL_TAB_COMMENTS tc
  ON tc.OWNER = t.OWNER
 AND tc.TABLE_NAME = t.TABLE_NAME
WHERE t.HAS_CODE = 1
  AND (t.HAS_TRADE_DATE + t.HAS_OPEN + t.HAS_CLOSE + t.HAS_PRECLOSE +
       t.HAS_ADJUST + t.HAS_VOLUME + t.HAS_AMOUNT + t.HAS_TRADE_STATE +
       t.HAS_NAV) > 0
ORDER BY MARKET_CAPABILITY_SCORE DESC, t.HAS_NAV DESC, t.TABLE_NAME;

-- Q29（limit=10）：WDZX 可见表、视图、物化视图和同义词的对象类型数量。
SELECT OBJECT_TYPE, COUNT(*) AS OBJECT_COUNT
FROM ALL_OBJECTS
WHERE OWNER = 'WDZX'
  AND OBJECT_TYPE IN ('TABLE','VIEW','MATERIALIZED VIEW','SYNONYM')
GROUP BY OBJECT_TYPE
ORDER BY OBJECT_TYPE;

-- Q30（limit=5）：可见同义词中指向 WDZX 的数量。
SELECT COUNT(*) AS SYNONYM_COUNT
FROM ALL_SYNONYMS
WHERE TABLE_OWNER = 'WDZX';

-- Q31（limit=100）：从表注释和字段注释反查 ETF、上市基金、IOPV、基金行情等对象。
SELECT SOURCE_TYPE, TABLE_NAME, COLUMN_NAME, COMMENT_TEXT
FROM (
  SELECT 'TABLE_COMMENT' AS SOURCE_TYPE, t.TABLE_NAME,
         CAST(NULL AS VARCHAR2(128)) AS COLUMN_NAME,
         t.COMMENTS AS COMMENT_TEXT
  FROM ALL_TAB_COMMENTS t
  WHERE t.OWNER = 'WDZX'
    AND REGEXP_LIKE(NVL(t.COMMENTS, ' '), 'ETF|上市基金|IOPV|基金.*行情', 'i')
  UNION ALL
  SELECT 'COLUMN_COMMENT', c.TABLE_NAME, c.COLUMN_NAME, c.COMMENTS
  FROM ALL_COL_COMMENTS c
  WHERE c.OWNER = 'WDZX'
    AND REGEXP_LIKE(NVL(c.COMMENTS, ' '),
                    '开盘价|收盘价|复权|成交量|成交额|ETF|上市基金|IOPV|基金.*行情', 'i')
)
ORDER BY TABLE_NAME, SOURCE_TYPE, COLUMN_NAME;

-- Q32（limit=20）：上交所、深交所、跨境、商品和已退市 ETF 的身份样本。
SELECT F_INFO_WINDCODE, F_INFO_NAME, F_INFO_TYPE, F_INFO_EXCHMARKET,
       F_INFO_LISTDATE, F_INFO_DELISTDATE, F_INFO_STATUS,
       LISTEDFUNDORNOT, S_INFO_INNERCODE, S_INFO_OUTERCODE
FROM WDZX.CHINAMUTUALFUNDDESCRIPTION
WHERE F_INFO_WINDCODE IN
      ('510300.SH','159919.SZ','513100.SH','518880.SH','515930.SH')
ORDER BY F_INFO_WINDCODE;

-- Q33（limit=30）：3 张股票行情/竞价候选表对 5 类 ETF 样本的记录和有效价格。
WITH sample_codes AS (
  SELECT '510300.SH' AS CODE FROM DUAL UNION ALL
  SELECT '159919.SZ' FROM DUAL UNION ALL
  SELECT '513100.SH' FROM DUAL UNION ALL
  SELECT '518880.SH' FROM DUAL UNION ALL
  SELECT '515930.SH' FROM DUAL
)
SELECT 'ASHAREEODPRICES' AS SOURCE_NAME, s.CODE,
       MIN(p.TRADE_DT) AS MIN_DT, MAX(p.TRADE_DT) AS MAX_DT,
       COUNT(p.S_INFO_WINDCODE) AS ROW_COUNT,
       COUNT(CASE WHEN p.S_DQ_OPEN > 0 THEN 1 END) AS VALID_OPEN_COUNT,
       COUNT(CASE WHEN p.S_DQ_CLOSE > 0 THEN 1 END) AS VALID_CLOSE_COUNT
FROM sample_codes s
LEFT JOIN WDZX.ASHAREEODPRICES p ON p.S_INFO_WINDCODE = s.CODE
GROUP BY s.CODE
UNION ALL
SELECT 'ASHAREEODPRICESMKT', s.CODE,
       MIN(p.TRADE_DT), MAX(p.TRADE_DT), COUNT(p.S_INFO_WINDCODE),
       COUNT(CASE WHEN p.S_DQ_OPEN > 0 THEN 1 END),
       COUNT(CASE WHEN p.S_DQ_CLOSE > 0 THEN 1 END)
FROM sample_codes s
LEFT JOIN WDZX.ASHAREEODPRICESMKT p ON p.S_INFO_WINDCODE = s.CODE
GROUP BY s.CODE
UNION ALL
SELECT 'ASHAREAUCTION', s.CODE,
       MIN(p.TRADE_DT), MAX(p.TRADE_DT), COUNT(p.S_INFO_WINDCODE),
       COUNT(CASE WHEN p.OPEN_AUCTION_PRICE > 0 AND p.OPEN_AUCTION_VOLUME > 0 THEN 1 END),
       COUNT(CASE WHEN p.CLOSE_AUCTION_PRICE > 0 AND p.CLOSE_AUCTION_VOLUME > 0 THEN 1 END)
FROM sample_codes s
LEFT JOIN WDZX.ASHAREAUCTION p ON p.S_INFO_WINDCODE = s.CODE
GROUP BY s.CODE
ORDER BY SOURCE_NAME, CODE;

-- Q34（limit=10）：上市基金集合竞价对 5 类 ETF 样本的日期和有效价量覆盖。
SELECT S_INFO_WINDCODE, MIN(TRADE_DT) AS MIN_DT, MAX(TRADE_DT) AS MAX_DT,
       COUNT(*) AS ROW_COUNT,
       COUNT(CASE WHEN OPEN_AUCTION_PRICE > 0 AND OPEN_AUCTION_VOLUME > 0 THEN 1 END) AS VALID_OPEN_COUNT,
       COUNT(CASE WHEN CLOSE_AUCTION_PRICE > 0 AND CLOSE_AUCTION_VOLUME > 0 THEN 1 END) AS VALID_CLOSE_COUNT,
       COUNT(CASE WHEN OPEN_AUCTION_PRICE > 0 AND OPEN_AUCTION_VOLUME > 0
                       AND CLOSE_AUCTION_PRICE > 0 AND CLOSE_AUCTION_VOLUME > 0
                  THEN 1 END) AS VALID_BOTH_COUNT
FROM WDZX.CHINACLOSEDFUNDAUCTION
WHERE S_INFO_WINDCODE IN
      ('510300.SH','159919.SZ','513100.SH','518880.SH','515930.SH')
GROUP BY S_INFO_WINDCODE
ORDER BY S_INFO_WINDCODE;

-- Q35（limit=10）：基金净值表对 5 类 ETF 样本的日期和关键字段非空覆盖。
SELECT F_INFO_WINDCODE, MIN(PRICE_DATE) AS MIN_DT, MAX(PRICE_DATE) AS MAX_DT,
       COUNT(*) AS ROW_COUNT, COUNT(F_NAV_UNIT) AS UNIT_NAV_COUNT,
       COUNT(F_NAV_ADJUSTED) AS ADJUSTED_NAV_COUNT,
       COUNT(F_NAV_ADJFACTOR) AS ADJ_FACTOR_COUNT
FROM WDZX.CHINAMUTUALFUNDNAV
WHERE F_INFO_WINDCODE IN
      ('510300.SH','159919.SZ','513100.SH','518880.SH','515930.SH')
GROUP BY F_INFO_WINDCODE
ORDER BY F_INFO_WINDCODE;

-- Q36（limit=10）：IOPV 表对 5 类 ETF 样本的日期和字段非空覆盖。
SELECT F_INFO_WINDCODE, MIN(PRICE_DATE) AS MIN_DT, MAX(PRICE_DATE) AS MAX_DT,
       COUNT(*) AS ROW_COUNT, COUNT(F_IOPV_NAV) AS IOPV_COUNT
FROM WDZX.CMFIOPVNAV
WHERE F_INFO_WINDCODE IN
      ('510300.SH','159919.SZ','513100.SH','518880.SH','515930.SH')
GROUP BY F_INFO_WINDCODE
ORDER BY F_INFO_WINDCODE;

-- Q37（limit=10）：业绩比较基准 EOD 接受 BI.WI 基准代码，而非 ETF 场内代码。
WITH codes AS (
  SELECT '510300.SH' AS CODE FROM DUAL UNION ALL
  SELECT '159919.SZ' FROM DUAL UNION ALL
  SELECT '510300BI.WI' FROM DUAL UNION ALL
  SELECT '159919BI.WI' FROM DUAL
)
SELECT c.CODE, MIN(p.TRADE_DT) AS MIN_DT, MAX(p.TRADE_DT) AS MAX_DT,
       COUNT(p.S_INFO_WINDCODE) AS ROW_COUNT,
       COUNT(p.S_DQ_CLOSE) AS CLOSE_COUNT,
       COUNT(p.S_DQ_PCTCHANGE) AS RETURN_COUNT
FROM codes c
LEFT JOIN WDZX.CHINAMUTUALFUNDBENCHMARKEOD p
  ON p.S_INFO_WINDCODE = c.CODE
GROUP BY c.CODE
ORDER BY c.CODE;

-- Q38（limit=10）：同日集合竞价、IOPV 与基金净值并列，验证三种用途和值均不同。
SELECT a.S_INFO_WINDCODE, a.TRADE_DT,
       a.OPEN_AUCTION_PRICE, a.CLOSE_AUCTION_PRICE,
       i.F_IOPV_NAV, n.F_NAV_UNIT, n.F_NAV_ADJUSTED, n.F_NAV_ADJFACTOR
FROM WDZX.CHINACLOSEDFUNDAUCTION a
LEFT JOIN WDZX.CMFIOPVNAV i
  ON i.F_INFO_WINDCODE = a.S_INFO_WINDCODE
 AND i.PRICE_DATE = a.TRADE_DT
LEFT JOIN WDZX.CHINAMUTUALFUNDNAV n
  ON n.F_INFO_WINDCODE = a.S_INFO_WINDCODE
 AND n.PRICE_DATE = a.TRADE_DT
WHERE a.S_INFO_WINDCODE IN ('510300.SH','159919.SZ','518880.SH')
  AND a.TRADE_DT = '20260916'
ORDER BY a.S_INFO_WINDCODE;

-- Q39（limit=10）：5 个代表性历史交易日的 ETF 池与集合竞价纵向覆盖。
WITH asof_dates AS (
  SELECT '20190801' AS ASOF_DT FROM DUAL UNION ALL
  SELECT '20210601' FROM DUAL UNION ALL
  SELECT '20230601' FROM DUAL UNION ALL
  SELECT '20250603' FROM DUAL UNION ALL
  SELECT '20260601' FROM DUAL
), etf_pool AS (
  SELECT DISTINCT x.ASOF_DT, s.F_INFO_WINDCODE AS CODE
  FROM asof_dates x
  JOIN WDZX.CHINAMUTUALFUNDSECTOR s
    ON s.S_INFO_SECTOR = '2001020200'
   AND s.S_INFO_SECTORENTRYDT <= x.ASOF_DT
   AND (s.S_INFO_SECTOREXITDT IS NULL OR s.S_INFO_SECTOREXITDT > x.ASOF_DT)
  JOIN WDZX.CHINAMUTUALFUNDDESCRIPTION d
    ON d.F_INFO_WINDCODE = s.F_INFO_WINDCODE
   AND d.LISTEDFUNDORNOT = 1
   AND d.F_INFO_LISTDATE <= x.ASOF_DT
   AND (d.F_INFO_DELISTDATE IS NULL OR d.F_INFO_DELISTDATE > x.ASOF_DT)
  WHERE s.F_INFO_WINDCODE LIKE '%.SH' OR s.F_INFO_WINDCODE LIKE '%.SZ'
)
SELECT e.ASOF_DT, COUNT(*) AS ETF_COUNT,
       COUNT(a.S_INFO_WINDCODE) AS WITH_AUCTION_ROW,
       COUNT(CASE WHEN a.OPEN_AUCTION_PRICE > 0 AND a.OPEN_AUCTION_VOLUME > 0 THEN 1 END) AS VALID_OPEN_COUNT,
       COUNT(CASE WHEN a.CLOSE_AUCTION_PRICE > 0 AND a.CLOSE_AUCTION_VOLUME > 0 THEN 1 END) AS VALID_CLOSE_COUNT,
       COUNT(CASE WHEN a.OPEN_AUCTION_PRICE > 0 AND a.OPEN_AUCTION_VOLUME > 0
                       AND a.CLOSE_AUCTION_PRICE > 0 AND a.CLOSE_AUCTION_VOLUME > 0
                  THEN 1 END) AS VALID_BOTH_COUNT,
       ROUND(100 * COUNT(CASE WHEN a.OPEN_AUCTION_PRICE > 0 AND a.OPEN_AUCTION_VOLUME > 0
                                  AND a.CLOSE_AUCTION_PRICE > 0 AND a.CLOSE_AUCTION_VOLUME > 0
                             THEN 1 END) / COUNT(*), 2) AS VALID_BOTH_PCT
FROM etf_pool e
LEFT JOIN WDZX.CHINACLOSEDFUNDAUCTION a
  ON a.S_INFO_WINDCODE = e.CODE
 AND a.TRADE_DT = e.ASOF_DT
GROUP BY e.ASOF_DT
ORDER BY e.ASOF_DT;

-- Q40（limit=10）：按调仓日前已公告净资产取规模前 50% 后的集合竞价覆盖。
WITH asof_dates AS (
  SELECT '20190801' AS ASOF_DT FROM DUAL UNION ALL
  SELECT '20210601' FROM DUAL UNION ALL
  SELECT '20230601' FROM DUAL UNION ALL
  SELECT '20250603' FROM DUAL UNION ALL
  SELECT '20260601' FROM DUAL
), etf_pool AS (
  SELECT DISTINCT x.ASOF_DT, s.F_INFO_WINDCODE AS CODE
  FROM asof_dates x
  JOIN WDZX.CHINAMUTUALFUNDSECTOR s
    ON s.S_INFO_SECTOR = '2001020200'
   AND s.S_INFO_SECTORENTRYDT <= x.ASOF_DT
   AND (s.S_INFO_SECTOREXITDT IS NULL OR s.S_INFO_SECTOREXITDT > x.ASOF_DT)
  JOIN WDZX.CHINAMUTUALFUNDDESCRIPTION d
    ON d.F_INFO_WINDCODE = s.F_INFO_WINDCODE
   AND d.LISTEDFUNDORNOT = 1
   AND d.F_INFO_LISTDATE <= x.ASOF_DT
   AND (d.F_INFO_DELISTDATE IS NULL OR d.F_INFO_DELISTDATE > x.ASOF_DT)
  WHERE s.F_INFO_WINDCODE LIKE '%.SH' OR s.F_INFO_WINDCODE LIKE '%.SZ'
), asset_candidates AS (
  SELECT e.ASOF_DT, e.CODE, p.F_PRT_NETASSET,
         ROW_NUMBER() OVER (
           PARTITION BY e.ASOF_DT, e.CODE
           ORDER BY p.F_PRT_ENDDATE DESC, p.F_ANN_DATE DESC, p.OPDATE DESC
         ) AS RN
  FROM etf_pool e
  JOIN WDZX.CHINAMUTUALFUNDASSETPORTFOLIO p
    ON p.S_INFO_WINDCODE = e.CODE
   AND p.F_ANN_DATE < e.ASOF_DT
   AND p.F_PRT_NETASSET > 0
), latest_asset AS (
  SELECT ASOF_DT, CODE, F_PRT_NETASSET
  FROM asset_candidates
  WHERE RN = 1
), ranked_asset AS (
  SELECT ASOF_DT, CODE, F_PRT_NETASSET,
         ROW_NUMBER() OVER (
           PARTITION BY ASOF_DT ORDER BY F_PRT_NETASSET DESC, CODE
         ) AS ASSET_RANK,
         COUNT(*) OVER (PARTITION BY ASOF_DT) AS ASSET_COUNT
  FROM latest_asset
), high_scale AS (
  SELECT ASOF_DT, CODE
  FROM ranked_asset
  WHERE ASSET_RANK <= CEIL(ASSET_COUNT * 0.5)
), pool_counts AS (
  SELECT ASOF_DT, COUNT(*) AS ETF_COUNT
  FROM etf_pool
  GROUP BY ASOF_DT
), asset_counts AS (
  SELECT ASOF_DT, COUNT(*) AS WITH_PIT_ASSET
  FROM latest_asset
  GROUP BY ASOF_DT
)
SELECT h.ASOF_DT, p.ETF_COUNT, c.WITH_PIT_ASSET,
       COUNT(*) AS HIGH_SCALE_COUNT,
       COUNT(a.S_INFO_WINDCODE) AS WITH_AUCTION_ROW,
       COUNT(CASE WHEN a.OPEN_AUCTION_PRICE > 0 AND a.OPEN_AUCTION_VOLUME > 0 THEN 1 END) AS VALID_OPEN_COUNT,
       COUNT(CASE WHEN a.CLOSE_AUCTION_PRICE > 0 AND a.CLOSE_AUCTION_VOLUME > 0 THEN 1 END) AS VALID_CLOSE_COUNT,
       COUNT(CASE WHEN a.OPEN_AUCTION_PRICE > 0 AND a.OPEN_AUCTION_VOLUME > 0
                       AND a.CLOSE_AUCTION_PRICE > 0 AND a.CLOSE_AUCTION_VOLUME > 0
                  THEN 1 END) AS VALID_BOTH_COUNT,
       ROUND(100 * COUNT(CASE WHEN a.OPEN_AUCTION_PRICE > 0 AND a.OPEN_AUCTION_VOLUME > 0
                                  AND a.CLOSE_AUCTION_PRICE > 0 AND a.CLOSE_AUCTION_VOLUME > 0
                             THEN 1 END) / COUNT(*), 2) AS VALID_BOTH_PCT
FROM high_scale h
JOIN pool_counts p ON p.ASOF_DT = h.ASOF_DT
JOIN asset_counts c ON c.ASOF_DT = h.ASOF_DT
LEFT JOIN WDZX.CHINACLOSEDFUNDAUCTION a
  ON a.S_INFO_WINDCODE = h.CODE
 AND a.TRADE_DT = h.ASOF_DT
GROUP BY h.ASOF_DT, p.ETF_COUNT, c.WITH_PIT_ASSET
ORDER BY h.ASOF_DT;

-- Q41（limit=10）：确认 5 个代表月份所用日期均为当月首个 SSE 交易日。
WITH months AS (
  SELECT '201908' AS YM FROM DUAL UNION ALL
  SELECT '202106' FROM DUAL UNION ALL
  SELECT '202306' FROM DUAL UNION ALL
  SELECT '202506' FROM DUAL UNION ALL
  SELECT '202606' FROM DUAL
)
SELECT m.YM, MIN(c.TRADE_DAYS) AS FIRST_TRADE_DAY
FROM months m
JOIN WDZX.ASHARECALENDAR c
  ON c.S_INFO_EXCHMARKET = 'SSE'
 AND c.TRADE_DAYS BETWEEN m.YM || '01' AND m.YM || '31'
GROUP BY m.YM
ORDER BY m.YM;

-- Q42（limit=5）：审计日有效开盘、有效收盘及其交集；三者不是互斥集合。
WITH etf AS (
  SELECT DISTINCT c.S_INFO_WINDCODE
  FROM WDZX.CHINAETFINVESTCLASS c
  JOIN WDZX.CHINAMUTUALFUNDDESCRIPTION d
    ON d.F_INFO_WINDCODE = c.S_INFO_WINDCODE
  WHERE d.LISTEDFUNDORNOT = 1
    AND d.F_INFO_STATUS = 101001000
    AND d.F_INFO_LISTDATE <= '20260916'
    AND (d.F_INFO_DELISTDATE IS NULL OR d.F_INFO_DELISTDATE > '20260916')
    AND (c.S_INFO_WINDCODE LIKE '%.SH' OR c.S_INFO_WINDCODE LIKE '%.SZ')
)
SELECT COUNT(*) AS IDENTIFIED_LIVE_ETFS,
       COUNT(a.S_INFO_WINDCODE) AS WITH_AUCTION_ROW,
       COUNT(CASE WHEN a.OPEN_AUCTION_PRICE > 0 AND a.OPEN_AUCTION_VOLUME > 0 THEN 1 END) AS WITH_VALID_OPEN_AUCTION,
       COUNT(CASE WHEN a.CLOSE_AUCTION_PRICE > 0 AND a.CLOSE_AUCTION_VOLUME > 0 THEN 1 END) AS WITH_VALID_CLOSE_AUCTION,
       COUNT(CASE WHEN a.OPEN_AUCTION_PRICE > 0 AND a.OPEN_AUCTION_VOLUME > 0
                       AND a.CLOSE_AUCTION_PRICE > 0 AND a.CLOSE_AUCTION_VOLUME > 0
                  THEN 1 END) AS WITH_VALID_BOTH,
       ROUND(100 * COUNT(CASE WHEN a.OPEN_AUCTION_PRICE > 0 AND a.OPEN_AUCTION_VOLUME > 0
                                  AND a.CLOSE_AUCTION_PRICE > 0 AND a.CLOSE_AUCTION_VOLUME > 0
                             THEN 1 END) / COUNT(*), 2) AS VALID_BOTH_PCT
FROM etf e
LEFT JOIN WDZX.CHINACLOSEDFUNDAUCTION a
  ON a.S_INFO_WINDCODE = e.S_INFO_WINDCODE
 AND a.TRADE_DT = '20260916';
